In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

In [40]:
import pandas as pd

In [ ]:
service = Service(executable_path='../chrome/chromedriver.exe')
options = webdriver.ChromeOptions()

In [33]:
driver = webdriver.Chrome(service=service, options=options)

In [34]:
driver.get("https://es.wikipedia.org/wiki/Anexo:Campeones_de_la_NBA")

In [35]:
element = driver.find_element(By.XPATH, '//*[@id="mw-content-text"]/div[1]/table[5]')
element

In [36]:
rows = element.find_elements(By.TAG_NAME, 'tr')
rows

[<selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.11")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.12")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.13")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.14")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.15")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.16")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.17")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.18")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.19")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.20")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.21")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.22")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.23")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.24")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.25")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.26")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.27")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.28")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.29")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.30")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.31")>,
 <selenium.webdriver.remote.webelement.WebElement (session="65e49d3d44855dcac1a2c12b6529534c", element="f.2C9EB2BD675EFC9C27FA674284785BB1.d.D812442A6C2BB6E19092065F517BC690.e.32")>]

In [48]:
team = []
championships = []
years = []

for row in rows:
    
    cells = row.find_elements(By.TAG_NAME, 'td')
    
    if not cells:
        cells = row.find_elements(By.TAG_NAME, 'th')
        
    cells_text = [cell.text for cell in cells]
    team.append(cells_text[0])
    championships.append(cells_text[1])
    years.append(cells_text[2])

In [43]:
team

['Equipo',
 'Boston Celtics',
 'Minneapolis/Los Angeles Lakers',
 'Philadelphia/Golden State Warriors',
 'Chicago Bulls',
 'San Antonio Spurs',
 'Detroit Pistons',
 'Miami Heat',
 'Syracuse Nationals/Philadelphia 76ers',
 'Houston Rockets',
 'New York Knicks',
 'Milwaukee Bucks',
 'Baltimore Bullets (extinto)n. 1',
 'Portland Trail Blazers',
 'Rochester Royals (hoy Sacramento Kings)',
 'Seattle SuperSonics (hoy Oklahoma City Thunder)',
 'St. Louis Hawks (hoy Atlanta Hawks)',
 'Washington Bullets (hoy Washington Wizards)',
 'Dallas Mavericks',
 'Cleveland Cavaliers',
 'Toronto Raptors',
 'Denver Nuggets']

In [59]:
dic = {'Teams': team[1:],
       'Championships': championships[1:],
       'Years': years[1:]}

dic

{'Teams': ['Boston Celtics',
  'Minneapolis/Los Angeles Lakers',
  'Philadelphia/Golden State Warriors',
  'Chicago Bulls',
  'San Antonio Spurs',
  'Detroit Pistons',
  'Miami Heat',
  'Syracuse Nationals/Philadelphia 76ers',
  'Houston Rockets',
  'New York Knicks',
  'Milwaukee Bucks',
  'Baltimore Bullets (extinto)n. 1',
  'Portland Trail Blazers',
  'Rochester Royals (hoy Sacramento Kings)',
  'Seattle SuperSonics (hoy Oklahoma City Thunder)',
  'St. Louis Hawks (hoy Atlanta Hawks)',
  'Washington Bullets (hoy Washington Wizards)',
  'Dallas Mavericks',
  'Cleveland Cavaliers',
  'Toronto Raptors',
  'Denver Nuggets'],
 'Championships': ['17',
  '17',
  '7',
  '6',
  '5',
  '3',
  '3',
  '3',
  '2',
  '2',
  '2',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1'],
 'Years': ['1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1968, 1969, 1974, 1976, 1981, 1984, 1986, 2008',
  '1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, 2009, 2010, 2020',
  '1947, 1956, 1975, 2015, 2017, 2018, 2022',
  '1991, 1992, 1993, 1996, 1997, 1998',
  '1999, 2003, 2005, 2007, 2014',
  '1989, 1990, 2004',
  '2006, 2012, 2013',
  '1955, 1967, 1983',
  '1994, 1995',
  '1970, 1973',
  '1971, 2021',
  '1948',
  '1977',
  '1951',
  '1979',
  '1958',
  '1978',
  '2011',
  '2016',
  '2019',
  '2023']}

In [60]:
df_NBA = pd.DataFrame(dic)
df_NBA

,Teams,Championships,Years
0,Boston Celtics,17,"1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965..."
1,Minneapolis/Los Angeles Lakers,17,"1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982..."
2,Philadelphia/Golden State Warriors,7,"1947, 1956, 1975, 2015, 2017, 2018, 2022"
3,Chicago Bulls,6,"1991, 1992, 1993, 1996, 1997, 1998"
4,San Antonio Spurs,5,"1999, 2003, 2005, 2007, 2014"
5,Detroit Pistons,3,"1989, 1990, 2004"
6,Miami Heat,3,"2006, 2012, 2013"
7,Syracuse Nationals/Philadelphia 76ers,3,"1955, 1967, 1983"
8,Houston Rockets,2,"1994, 1995"
9,New York Knicks,2,"1970, 1973"
10,Milwaukee Bucks,2,"1971, 2021"
11,Baltimore Bullets (extinto)n. 1,1,1948
12,Portland Trail Blazers,1,1977
13,Rochester Royals (hoy Sacramento Kings),1,1951
14,Seattle SuperSonics (hoy Oklahoma City Thunder),1,1979
15,St. Louis Hawks (hoy Atlanta Hawks),1,1958
16,Washington Bullets (hoy Washington Wizards),1,1978
17,Dallas Mavericks,1,2011
18,Cleveland Cavaliers,1,2016
19,Toronto Raptors,1,2019
20,Denver Nuggets,1,2023

In [69]:
df_NBA.index = pd.RangeIndex(start=1, stop=len(df_NBA) + 1, step=1)

In [70]:
df_NBA

,Teams,Championships,Years
1,Boston Celtics,17,"1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965..."
2,Minneapolis/Los Angeles Lakers,17,"1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982..."
3,Philadelphia/Golden State Warriors,7,"1947, 1956, 1975, 2015, 2017, 2018, 2022"
4,Chicago Bulls,6,"1991, 1992, 1993, 1996, 1997, 1998"
5,San Antonio Spurs,5,"1999, 2003, 2005, 2007, 2014"
6,Detroit Pistons,3,"1989, 1990, 2004"
7,Miami Heat,3,"2006, 2012, 2013"
8,Syracuse Nationals/Philadelphia 76ers,3,"1955, 1967, 1983"
9,Houston Rockets,2,"1994, 1995"
10,New York Knicks,2,"1970, 1973"
11,Milwaukee Bucks,2,"1971, 2021"
12,Baltimore Bullets (extinto)n. 1,1,1948
13,Portland Trail Blazers,1,1977
14,Rochester Royals (hoy Sacramento Kings),1,1951
15,Seattle SuperSonics (hoy Oklahoma City Thunder),1,1979
16,St. Louis Hawks (hoy Atlanta Hawks),1,1958
17,Washington Bullets (hoy Washington Wizards),1,1978
18,Dallas Mavericks,1,2011
19,Cleveland Cavaliers,1,2016
20,Toronto Raptors,1,2019
21,Denver Nuggets,1,2023